### PR TITLE
Fix some Tile memory safety issues

### LINKED ISSUE #73: Crash when closing the Stonesense window when a fort is loaded (Linux)
On Linux, closing the Stonesense window also closes the Dwarf Fortress window, terminating the application

### PR DESCRIPTION
**Pull request by lethosor**
0fb9abc5f8a7511269ab072317bbd366bc2fa9ca introduced some paths where Tile instances could be double-freed: specifically, `WorldSegment::Reset()` would call `Tile::InvalidateAndDestroy()` on individual tiles, followed by `delete[]` on the array containing them, and both of these call the Tile destructor.

Fixes an issue reported on Discord, and also fixes #73 (at least from my initial testing).

Marking as a draft because I would like to potentially revisit how Tile instances are stored. They contain at least one non-POD object (`Tile::building::sprites` is a vector, and in fact was what usually triggered the crash on my end), and the changes here _might_ result in some memory leaks if those are not freed properly.

### CODE REVIEW

File: Tile.h [hunk 1]
```diff
@@ -127,6 +127,8 @@ class Tile
     bool Invalidate();
     static bool InvalidateAndDestroy(Tile*);
     static bool CleanCreateAndValidate(Tile*, WorldSegment*, df::tiletype);
+
+    friend class WorldSegment;
```
Comment (lethosor) [inline Tile.h:131]: Added by me to allow WorldSegment to access `Tile::valid` directly. `memset()` was used previously.

File: WorldSegment.h [hunk 2]
```diff
@@ -46,7 +46,11 @@ class WorldSegment
 
         uint32_t newNumTiles = inState.Size.x * inState.Size.y * inState.Size.z;
         uint32_t memoryNeeded = newNumTiles * sizeof(Tile);
-        tiles = new Tile[newNumTiles];
+        tiles = (Tile *)new char[memoryNeeded];
+        //memset(tiles, 0, memoryNeeded);
+        for(uint32_t i = 0; i < newNumTiles; i++) {
+            tiles[i].valid = false;
```
Comment (lethosor) [inline WorldSegment.h:52]: Another reason I'd like to switch towards allocating/deallocating `Tile`s instead of managing memory manually: the default `Tile` constructor already sets `valid` to `false`, so this logic (also present below) would be unnecessary.

File: Tile.cpp [hunk 3]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-    downstairborders = 0;
-    lightborders = 0;
-
-    fog_of_war = false;
-
-    rampindex = 0;
-
-    deepwater = 0;
-
-    flow_direction = tile_liquid_flow_dir::none;
```
Comment (Cyprex) [inline Tile.cpp:104]: This isn't necessarily the same as memset(0) on the field, did you check?

File: Tile.cpp [hunk 4]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-
-    consForm = 0;
-
-    obscuringCreature = false;
-    obscuringBuilding = false;
-
-    tileeffect.matt.type = 0;
-    tileeffect.matt.index = 0;
-    tileeffect.density = 0;
-    tileeffect.type = flow_type::Miasma;
```
Comment (Cyprex) [inline Tile.cpp:134]: Not 0

File: Tile.cpp [hunk 5]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-
-    memset(&Item, 0, sizeof(Item));
-
-    building.info = nullptr;
-    building.type = building_type::Chair;
```
Comment (Cyprex) [inline Tile.cpp:139]: Not 0

File: Tile.cpp [hunk 6]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-    building.sprites.clear();
```
Comment (Cyprex) [inline Tile.cpp:140]: Side effects here

File: Tile.cpp [hunk 7]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-    building.parent = nullptr;
-    building.constructed_mats.clear();
```
Comment (Cyprex) [inline Tile.cpp:142]: Side effects again

File: WorldSegment.h [hunk 8]
```diff
@@ -46,7 +46,11 @@ class WorldSegment
 
         uint32_t newNumTiles = inState.Size.x * inState.Size.y * inState.Size.z;
         uint32_t memoryNeeded = newNumTiles * sizeof(Tile);
-        tiles = new Tile[newNumTiles];
+        tiles = (Tile *)new char[memoryNeeded];
```
Comment (Cyprex) [inline WorldSegment.h:49]: This allocates a lot less memory than previously, it appears way too much was allocated before?

Comment (Cyprex) [reply WorldSegment.h:49]: I assume you're allocating(and later freeing) chars to avoid constructor/destructor calls?

File: Tile.cpp (hunk 3 above)
Comment (quietust) [reply Tile.cpp:104]: `tile_liquid_flow_dir::none` is zero, so this one's fine.

File: Tile.cpp (hunk 4 above)
Comment (quietust) [reply Tile.cpp:134]: Actually, this one is also zero:
```
    <enum-type type-name='flow_type' base-type='int16_t'>
        <enum-item name='Miasma'/>
...

File: Tile.cpp [hunk 9]
```diff
@@ -61,89 +61,7 @@ worn_item::worn_item()
...
-
-    creature = nullptr;
-    tree.type = 0;
-    tree.index = 0;
-    tree_tile.whole = 0;
-
-    mudlevel = 0;
-    snowlevel = 0;
-    bloodlevel = 0;
-    bloodcolor = al_map_rgba(0,0,0,0);
```
[the remark this answers is not in the document]
Comment (quietust) [reply Tile.cpp:117]: Good point - that should probably get added to the original constructor below (which sets all of the "nonzero values").

File: Tile.cpp (hunk 6 above)
Comment (quietust) [reply Tile.cpp:140]: This never should have been here in the first place - this was a *constructor*, and the default constructor would have initialized all vectors to be empty anyways.

File: Tile.cpp (hunk 7 above)
Comment (quietust) [reply Tile.cpp:142]: See above

File: Tile.cpp [hunk 10]
```diff
@@ -186,18 +104,6 @@ bool Tile::IsValid()
     return valid;
 }
 
-/**
```
Comment (quietust) [inline Tile.cpp:189]: This function was originally used for marking tiles as unused; it was removed because it was almost guaranteed to leak memory (since it would mark the objects as freed without calling the destructor).

I suppose in theory this could've been used instead of manually setting `valid=false;` on every tile immediately after allocation, but it would've been significantly slower.

File: Tile.cpp (hunk 5 above)
Comment (quietust) [reply Tile.cpp:139]: Incorrect, this one is also zero:
```
    <enum-type type-name='building_type'>
        <enum-attr name='name' use-key-name='true'/>
        <enum-attr name='classname'/>

        <enum-item name="NONE" value='-1'/>

        <enum-item name="Chair">
            <item-attr name='classname' value='building_chairst'/>
        </enum-item>
```
This also doesn't matter because the real constructor initializes it to `BUILDINGTYPE_NA`.

File: WorldSegment.h (hunk 2 above)
Comment (quietust) [reply WorldSegment.h:52]: I was just changing this to (mostly) match its original functionality before the commit that broke it - changing it to allocate/deallocate individual `Tile`s might result in severe performance penalties (which is probably why it was done this way in the first place).

**Comment by quietust** [comment]
The primary goal of this patch is to _revert_ the changes that caused the crashes on Linux - further _improvements_ to the logic should probably be done in another patch.

**Comment by lethosor** [comment]
Yeah, I think we can go with this. Of note, the `Tile()` constructor commented on by @Cyprex isn't used at all now (it was added in 0fb9abc5f8a7511269ab072317bbd366bc2fa9ca to accomocate `new Tile[]`). `memset` should zero out all fields appropriately. I am still concerned about it leaking vectors' memory, but this is good to have to resolve the immediate crash.
