### PR TITLE
Megashot Fix

### LINKED ISSUE #144: allow stonesense to continue working after a mega screenshot

### PR DESCRIPTION
**Pull request by realSquidCoder**
Revert #102 as its not needed anymore
Fixes #144

### CODE REVIEW

**Comment by NicksWorld** [comment]
It is my understanding initial bug that lead to #102 has been fixed in #140. The only assert I could see possibly being hit was ensuring bitmap drawing wasn't held, which likely was caused by the extraneous call removed in #140.

If this is indeed the case, stonesense no longer has a need to become unresponsive following a megashot. The only change that should be needed, outside of reverting #102, is to backup `lift_segment_offscreen_x/y` and restore at the end of the function.

**Comment by myk002** [comment]
Agree with NicksWorld
realSquidCoder, could you try reverting the logic changes in https://github.com/DFHack/stonesense/pull/102/files and verifying that this issue still exists?

**Comment by realSquidCoder** [comment]
the crash is gone and a new issue has arisen in its stead: the map no longer gets drawn
image

I have confirmed that it still responds and tracks df etc

**Comment by realSquidCoder** [comment]
now works as intended

File: GUI.cpp [hunk 1]
```diff
@@ -1339,19 +1340,22 @@ void saveMegashot(bool tall)
 
 
         al_save_bitmap(filename.string().c_str(), bigFile);
-        // al_set_target_bitmap(al_get_backbuffer(al_get_current_display()));
-        // timer = clock() - timer;
-        // PrintMessage("\tcreating screenshot took %ims\n", timer);
+        al_set_target_bitmap(al_get_backbuffer(al_get_current_display()));
+        timer = clock() - timer;
+        PrintMessage("\tcreating screenshot took %ims\n", timer);
```
Comment (NicksWorld) [inline GUI.cpp:1345]: Clock uses clock_t which is not milliseconds, see #175 for how go convert to ms.

File: main.cpp [hunk 2]
```diff
@@ -221,6 +221,8 @@ static void main_loop(ALLEGRO_DISPLAY * display, ALLEGRO_EVENT_QUEUE *queue, ALL
 
     ALLEGRO_EVENT event;
     while (!al_get_thread_should_stop(main_thread)) {
+        if (stonesenseState.timeToCloseWindow) { return;}
```
Comment (NicksWorld) [inline main.cpp:224]: This shouldn't be needed as we can already use al_set_thread_should_stop(stonsense_event_thread)

File: GUI.cpp (hunk 1 above)
Comment (realSquidCoder) [reply GUI.cpp:1345]: so i need to do `clockToMS(timer);`?

File: main.cpp (hunk 2 above)
Comment (realSquidCoder) [reply main.cpp:224]: no ok im leaving that in there bc this is useful to debug to dbug with

File: StonesenseState.h [hunk 3]
```diff
@@ -27,6 +27,7 @@ class StonesenseState
     FrameTimers stoneSenseTimers;
     bool timeToReloadSegment;
     bool timeToReloadConfig;
+    bool timeToCloseWindow;
```
Comment (myk002) [inline StonesenseState.h:30]: leftover?

File: main.cpp (hunk 2 above)
Comment (myk002) [reply main.cpp:224]: `timeToCloseWindow` is never set. how is it useful for debugging?

File: StonesenseState.h (hunk 3 above)
Comment (realSquidCoder) [reply StonesenseState.h:30]: No, new var for debugging and future use.

Comment (myk002) [reply StonesenseState.h:30]: You can keep it in a local branch, but as it is, this is just confusing to have in the mainline code

**Review by myk002 — APPROVED** [review]
